version: "3.1"
services:

  database:
    image: postgres:11-alpine
    container_name: docler-test-app-postgres
    volumes:
      - ./app:/app
      - ./postgres-dump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    networks:
      - symfony

  webserver:
    image: nginx:alpine
    container_name: docler-test-app-webserver
    working_dir: /app
    volumes:
        - ./app:/app
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    networks:
      - symfony

  php-fpm:
    build: phpdocker/php-fpm
    container_name: docler-test-app-php-fpm
    working_dir: /app
    volumes:
      - ./app:/app
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - symfony

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: docler-test-app-rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq:cached
    ports:
      - 15672:15672
    networks:
      - symfony

  php-consumer:
    build: phpdocker/php-consumer
    container_name: docler-test-app-php-consumer
    working_dir: /app
    volumes:
      - ./app:/app
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - symfony

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - symfony

volumes:
  rabbitmq:

networks:
  symfony: